# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timetamp')),
                ('x', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='x')),
                ('y', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='y')),
                ('z', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='z')),
            ],
        ),
        migrations.CreateModel(
            name='AngleAcceleration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timetamp')),
                ('x', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='x')),
                ('y', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='y')),
                ('z', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='z')),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('a', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='a')),
                ('b', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='b')),
                ('c', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='c')),
                ('d', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='d')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_strength', models.IntegerField(verbose_name='signal_strength')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('steps', models.IntegerField(verbose_name='steps')),
                ('start_time', models.BigIntegerField(verbose_name='start_time')),
                ('end_time', models.BigIntegerField(verbose_name='end_time')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='token')),
                ('expire', models.BigIntegerField(verbose_name='expire')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='name')),
                ('password', models.CharField(max_length=30)),
                ('real_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='real_name')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='weight')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='height')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='sex')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteApp.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Velocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('velocity', models.FloatField(verbose_name='velocity')),
                ('distance', models.FloatField(verbose_name='distance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteApp.User')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysiteApp.User'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscribe_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_from', to='mysiteApp.User'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscribe_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_to', to='mysiteApp.User'),
        ),
        migrations.AddField(
            model_name='step',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteApp.User'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteApp.User'),
        ),
        migrations.AddField(
            model_name='angleacceleration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteApp.User'),
        ),
        migrations.AddField(
            model_name='acceleration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteApp.User'),
        ),
    ]
